{{ if .Values.choreoDefaultValues.enableDefaultOrgAndProject }}
apiVersion: core.choreo.dev/v1
kind: DataPlane
metadata:
  name: {{ .Values.choreoDefaultValues.dataPlane.name}}
  namespace: {{ .Values.choreoDefaultValues.dataPlane.namespace}}
  annotations:
    core.choreo.dev/display-name: {{ .Values.choreoDefaultValues.dataPlane.displayName }}
    core.choreo.dev/description: {{ .Values.choreoDefaultValues.dataPlane.description }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8"
  labels:
    core.choreo.dev/organization: {{ .Values.choreoDefaultValues.dataPlane.organization }}
    core.choreo.dev/name: {{ .Values.choreoDefaultValues.dataPlane.name}}
spec:
  kubernetesCluster:
  {{- toYaml .Values.choreoDefaultValues.dataPlane.kubernetesCluster | nindent 4 }}
  gateway:
    publicVirtualHost: {{ .Values.choreoDefaultValues.dataPlane.externalGatewayVirtualHost }}
    organizationVirtualHost: {{ .Values.choreoDefaultValues.dataPlane.internalGatewayVirtualHost }}
{{ end }}
