apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - reading-list-service-workload.yaml
  - reading-list-service-endpoint.yaml

labels:
  - pairs:
      choreo.dev/project: default-project
      choreo.dev/environment: production