{{ if .Values.choreoDefaultValues.enableDefaultOrgAndProject }}
apiVersion: openchoreo.dev/v1
kind: Project
metadata:
  name: {{ .Values.choreoDefaultValues.DefaultProject.name }}
  namespace: {{ .Values.choreoDefaultValues.DefaultProject.namespace }}
  annotations:
    openchoreo.dev/display-name: {{ .Values.choreoDefaultValues.DefaultProject.displayName }}
    openchoreo.dev/description: {{ .Values.choreoDefaultValues.DefaultProject.description }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "11"
  labels:
    openchoreo.dev/organization: {{ .Values.choreoDefaultValues.DefaultProject.organization }}
    openchoreo.dev/name: {{ .Values.choreoDefaultValues.DefaultProject.name }}
spec:
  deploymentPipelineRef: {{ .Values.choreoDefaultValues.deploymentPipeline.name }}
{{ end }}
