apiVersion: openchoreo.dev/v1alpha1
kind: ServiceClass
metadata:
  labels:
    app.kubernetes.io/name: choreo
    app.kubernetes.io/managed-by: kustomize
  name: serviceclass-sample
spec:
  # TODO(user): Add fields here
