apiVersion: openchoreo.dev/v1alpha1
kind: ConfigurationGroup
metadata:
  labels:
    app.kubernetes.io/name: choreo
    app.kubernetes.io/managed-by: kustomize
  name: configurationgroup-sample
spec:
  # TODO(user): Add fields here
