apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "choreo-controllers.fullname" . }}-deployableartifact-editor-role
  labels:
  {{- include "choreo-controllers.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.choreo.dev
  resources:
  - deployableartifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - deployableartifacts/status
  verbs:
  - get
