apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "choreo-control-plane.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "choreo-control-plane.fullname" . }}-serving-cert
  labels:
  {{- include "choreo-control-plane.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "choreo-control-plane.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-openchoreo-dev-v1alpha1-project
  failurePolicy: Fail
  name: mproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openchoreo.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
  sideEffects: None
