apiVersion: v2
name: openchoreo-build-plane
description: A Helm chart for OpenChoreo Build Plane
type: application

# Version strategy: latest-dev for development, replaced by CI for releases
version: 0.0.0-latest-dev
appVersion: "latest-dev"

home: https://github.com/openchoreo/openchoreo
icon: https://openchoreo.github.io/img/openchoreo_logo.png
sources:
  - https://github.com/openchoreo/openchoreo
keywords:
  - openchoreo
  - internal-developer-platform
  - idp
  - kubernetes
  - build-automation
  - ci-cd
  - argo-workflows
  - devops
maintainers:
  - name: OpenChoreo Team
    url: https://github.com/openchoreo/openchoreo
dependencies:
  - name: argo-workflows
    repository: "https://argoproj.github.io/argo-helm"
    version: 0.45.2
