---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: endpointv2s.core.choreo.dev
spec:
  group: core.choreo.dev
  names:
    kind: EndpointV2
    listKind: EndpointV2List
    plural: endpointv2s
    singular: endpointv2
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: EndpointV2 is the Schema for the endpointv2s API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: EndpointV2Spec defines the desired state of EndpointV2.
            properties:
              className:
                type: string
              environmentName:
                minLength: 1
                type: string
              owner:
                properties:
                  componentName:
                    minLength: 1
                    type: string
                  projectName:
                    minLength: 1
                    type: string
                required:
                - componentName
                - projectName
                type: object
              rest:
                properties:
                  backend:
                    properties:
                      basePath:
                        type: string
                      port:
                        format: int32
                        type: integer
                    required:
                    - port
                    type: object
                  operations:
                    items:
                      properties:
                        description:
                          type: string
                        exposeLevels:
                          items:
                            type: string
                          type: array
                        method:
                          type: string
                        path:
                          type: string
                        scopes:
                          items:
                            type: string
                          type: array
                      required:
                      - method
                      - path
                      type: object
                    type: array
                type: object
              type:
                description: EndpointType defines the different API technologies supported
                  by the endpoint
                type: string
            required:
            - className
            - environmentName
            - owner
            - type
            type: object
          status:
            description: EndpointV2Status defines the observed state of EndpointV2.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
