name: Release

on:
  # Manual Release
  workflow_dispatch:
  # TODO: Add a tag to trigger the release and remove the branch push trigger
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: GitHub Container Registry Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker Build and Push
        run: |
          make docker-build docker-push docker-push-latest

      - name: Helm Registry Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Helm Package and Push
        run: |
          # Fix to remove tag from generated helmify values.yaml 
          # See: https://github.com/arttor/helmify/issues/15
          sed -i '/^[[:space:]]*tag:/d' install/helm/choreo/values.yaml
          make helm-dependency-build helm-package helm-push

